# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
###新增区域
POST http://localhost:8006/addArea
Content-Type: application/json

{
   "Area": {
     "areaName": "区域一",
     "folderId": 6
   },
  "devices": [330119520001076203,330119520001191003]
}

###删除区域
POST http://localhost:8006/removeArea
Content-Type: application/json

{
   "id": "2"
}

###修改区域下的设备名称
POST http://localhost:8006/updateArea
Content-Type: application/json

{
  "AreaBean": {
    "id": 2,
    "areaName": "区域一更改后",
    "folderId": 1
  },
  "devices": [1,2,3]
}

###



###获取一个区域下的所有设备
POST http://localhost:8006/readArea
Content-Type: application/json

{
    "id": "8"
}

###修改区域名称
POST http://localhost:8006/updateAreaName
Content-Type: application/json

{
    "id": "7",
  "areaName": "嫌疑人活动范围",
  "folderId": "8"
}

###
[
{
type：“1”，
ids:[1,1.3]
},

]