# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
#多边形
POST localhost:8006/boxselect
Content-Type: application/json

[
  {
    "Longitude":"120.156",
    "Latitude":"30.257"
  },
  {
    "Longitude":"120.157",
    "Latitude":"30.257"
  },
  {
    "Longitude":"120.157",
    "Latitude":"30.256"
  },
  {
    "Longitude":"120.156",
    "Latitude":"30.256"
  }

]

### 圆形
POST localhost:8006/roundboxselect
Content-Type: application/json

{
  "pointBean":{
    "longitude":"120.16402189355016",
    "latitude":"30.256200718096633"
  },
  "radius":"0.004002413023"
}

###