# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
###增加文件夹
POST http://localhost:8006/addFolder
Content-Type: application/json

{
  "folderName":"631案情"
}

###删除文件夹
POST http://localhost:8006/removeFolder
Content-Type: application/json

{
  "id":"4"
}

###修改文件夹状态
POST http://localhost:8006/setFolderStatus
Content-Type: application/json

{
  "id": "9"
}

###修改文件夹名称
POST http://localhost:8006/setFolderName
Content-Type: application/json

{
  "id": "9",
  "folderName": "630绝密案情"

}

###根据状态展示文件夹
POST http://localhost:8006/getFolderByStatus
Content-Type: application/json

{
  "status": 0,
  "pageSize": 1,
  "pageNumber":4
}

###展示所有文件夹
POST http://localhost:8006/readAllFolder
Content-Type: application/json

###展示文件夹下的详情
POST http://localhost:8006/readFolder
Content-Type: application/json

{
    "id": 61,
  "pageSize": 15,
  "pageNumber": 1
}

###

###模糊搜索文件夹
POST http://localhost:8006/getFolderByName
Content-Type: application/json

{
  "folderName": "案"

}

###总和信息接口
POST http://localhost:8006/totalInfo
Content-Type: application/json

{}

###