# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


###功能模块使用统计
POST http://localhost:8006/screenFloatingFunctionUseNumber
Content-Type: application/json

###视频路数统计
POST http://localhost:8006/screenFloatingVideoPathNumber
Content-Type: application/json

###报警统计
POST http://localhost:8006/screenFloatingAlaramNumber
Content-Type: application/json

###分局算力分配
POST http://localhost:8006/screenFloatingCureauDeviceDistribution
Content-Type: application/json
###视频巡逻统计
POST http://localhost:8006/screenFloatingVideoPatrolNumber
Content-Type: application/json
###当日抓拍统计
POST http://localhost:8006/screenFloatingSnapNumberToday
Content-Type: application/json

###


