# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
###
POST http://{{host}}:8002/v3/access_device_list
Content-Type: {{content}}

###
POST http://{{host}}:8006/camera_list HTTP/1.1
Content-Type: {{content}}

###