# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
###增加一个轨迹
POST http://localhost:8006/addtrack
Content-Type: application/json

{
  "track":{
      "trackName": "犯罪嫌疑人轨迹",
      "folderId": "6"
  },
  "pictureList": [{
    "cropImageSignedUrl": "111",
    "origImageUrl": "111",
    "cropImageUrl": "111",
    "oriImageSignedUrl": "111",
    "pictureTime": "123456",
    "pictureId": "8888",
    "deviceId": "7",
    "score": "199"
  },{
    "cropImageSignedUrl": "666",
    "origImageUrl": "666",
    "cropImageUrl": "666",
    "oriImageSignedUrl": "666",
    "pictureTime": "123456",
    "pictureId": "88889",
    "deviceId": "7",
    "score": "199"
  }]
}

###修改轨迹名称
POST http://localhost:8006/updatetrackname
Content-Type: application/json

{
  "trackName": "Akun轨迹",
  "id": "2"
}

###删除轨迹
POST http://localhost:8006/removetrack
Content-Type: application/json

{
  "id": "7"
}

###