# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8006/addtrack
Content-Type: application/json

{
  "track":{
      "trackName": "akun轨迹",
      "folderId": "2"
  },
  "pictureList": [{
    "cropImageSignedUrl": "111",
    "origImageUrl": "111",
    "cropImageUrl": "111",
    "oriImageSignedUrl": "111",
    "pictureTime": "123456",
    "deviceId": "7",
    "folderId": "1",
    "score": "199"
  },{
    "cropImageSignedUrl": "666",
    "origImageUrl": "666",
    "cropImageUrl": "666",
    "oriImageSignedUrl": "666",
    "pictureTime": "123456",
    "deviceId": "7",
    "folderId": "1",
    "score": "199"
  }]
}

###